global:
  scrape_interval: 15s  # Scrape metrics every 15 seconds

scrape_configs:
  - job_name: 'aws_ec2'
    ec2_sd_configs:
      - region: us-west-2  # Specify the AWS region
        access_key: 'AWS_ACCESS_KEY'  # Optional: Use IAM roles for better security
        secret_key: 'AWS_SECRET_KEY'
    relabel_configs:
      - source_labels: [__meta_ec2_instance_id]
        target_label: instance_id
      - source_labels: [__meta_ec2_private_ip]
        target_label: instance_ip
