apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-website-deployment
  labels:
    app: static-website
spec:
  replicas: 2  # Number of replicas (pods) to run
  selector:
    matchLabels:
      app: static-website
  template:
    metadata:
      labels:
        app: static-website
    spec:
      containers:
        - name: static-website
          image: <your-docker-image>  # Use your Docker image, e.g., static-website:latest
          ports:
            - containerPort: 80